### ISSUE TITLE
Background mask not taking full height in android

### ISSUE THREAD

**Issue by ShivamJoker** [xcarpentier/rn-tourguide#50] opened 2021-04-29 09:56 UTC
As you can see in the image there is some space left in the bottom.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/23727670/116533299-d6923e00-a8fe-11eb-89fa-1f89142a2ae6.png">

These are providers I am using
```jsx
const App = () => (
  <ColorSchemeProvider>
    <BottomSheetModalProvider>
      <SafeAreaProvider>
        <TourGuideProvider
          androidStatusBarVisible={true}
          animationDuration={250}>
          <StatusBar
            barStyle="dark-content"
            backgroundColor="#c8b900"
            translucent
          />
          <AppContent />
        </TourGuideProvider>
      </SafeAreaProvider>
    </BottomSheetModalProvider>
  </ColorSchemeProvider>
);
```

Full code can be seen here - https://github.com/ShivamJoker/SQL-Play/blob/d409f4b0c06323c022ed99a6e5384c0ff66d4a83/src/component/App.tsx#L205

**Comment by Md-Mudassir** [comment] 2021-05-19 06:36
I'm also facing the same issue.. did you find any fix? @ShivamJoker

**Comment by ShivamJoker** [comment] 2021-05-19 06:58
@Md-Mudassir no, this library seems unmaintained

**Comment by i-kelly** [comment] 2021-06-16 08:50
> @Md-Mudassir no, this library seems unmaintained

https://github.com/xcarpentier/rn-tourguide/blob/c22e6c339871f1bc67e858c0c140212f478b9658/src/components/SvgMask.tsx#L42
I change this code  and full screen 
const FIRST_PATH = `M0,0H${screenDimensions.width}V${  screenDimensions.height + StatusBar.currentHeight}H0V0ZM${screenDimensions.width / 2},${  screenDimensions.height / 2} h 1 v 1 h -1 Z`

**Comment by Md-Mudassir47** [comment] 2021-06-16 09:11
> > @Md-Mudassir no, this library seems unmaintained
> 
> https://github.com/xcarpentier/rn-tourguide/blob/c22e6c339871f1bc67e858c0c140212f478b9658/src/components/SvgMask.tsx#L42
> 
> 
> I change this code and full screen
> const FIRST_PATH = `M0,0H${screenDimensions.width}V${ screenDimensions.height + StatusBar.currentHeight}H0V0ZM${screenDimensions.width / 2},${ screenDimensions.height / 2} h 1 v 1 h -1 Z`

how do i use the change? i tried to change the code in node_modules inside rn-tourguide folder but the code seems different in that for this file

**Comment by Md-Mudassir47** [comment] 2021-06-16 09:19
> > @Md-Mudassir no, this library seems unmaintained
> 
> https://github.com/xcarpentier/rn-tourguide/blob/c22e6c339871f1bc67e858c0c140212f478b9658/src/components/SvgMask.tsx#L42
> 
> 
> I change this code and full screen
> const FIRST_PATH = `M0,0H${screenDimensions.width}V${ screenDimensions.height + StatusBar.currentHeight}H0V0ZM${screenDimensions.width / 2},${ screenDimensions.height / 2} h 1 v 1 h -1 Z`

Thank you so much, It worked

**Comment by i-kelly** [comment] 2021-06-16 09:42
> > > @Md-Mudassir no, this library seems unmaintained
> > 
> > 
> > https://github.com/xcarpentier/rn-tourguide/blob/c22e6c339871f1bc67e858c0c140212f478b9658/src/components/SvgMask.tsx#L42
> > 
> > I change this code and full screen
> > const FIRST_PATH = `M0,0H${screenDimensions.width}V${ screenDimensions.height + StatusBar.currentHeight}H0V0ZM${screenDimensions.width / 2},${ screenDimensions.height / 2} h 1 v 1 h -1 Z`
> 
> Thank you so much, It worked

I use patch-package library in my project 
[https://github.com/ds300/patch-package](url)

**Comment by DvillamizarM** [comment] 2021-09-12 23:59
hello the above solution did not work for me in node_modules\rn-tourguide\lib\components\SvgMask.js
i changed the window dimensions from 'window' to 'screen' and that fixed the shadow issue .. but the unshaded area is still higher than it should be

**Comment by Md-Mudassir47** [comment] 2021-09-13 05:15
> hello the above solution did not work for me in node_modules\rn-tourguide\lib\components\SvgMask.js
> i changed the window dimensions from 'window' to 'screen' and that fixed the shadow issue .. but the unshaded area is still higher than it should be

Try the below code (replace it here `/node_modules/rn-tourguide/lib/components/SvgMask.js`) .. for me it worked

```js
const screenDimensions = Dimensions.get('screen')
const FIRST_PATH = `M0,0H${screenDimensions.width}V${screenDimensions.height}H0V0ZM${screenDimensions.width / 2},${screenDimensions.height / 2} h 1 v 1 h -1 Z
```

**Comment by spideyinf** [comment] 2021-12-10 09:01
Same issue for me on Android

**Comment by evanlarkin10** [comment] 2022-01-03 21:53
I'm having this issue on android, the tabbar is not part of the masked area. In version 3.2.0 this solution is implemented and the issue is still happening.

**Comment by xcarpentier** [comment] 2022-01-21 09:01
Can someone make an MR of it?

**Comment by gigeos** [comment] 2022-01-31 10:20
For my part, I just add a little timeout and now it's well displayed

**Comment by lucidprojects** [comment] 2022-06-01 21:04
A bit of a hack but I just adjust the canvasSize a bit by adding to the calculated screen height `height + PX`.  Works well in both iOS and Android and with both tourguide version 3.2.0 and 2.7.1

```
this.handleLayout = ({ nativeEvent: { layout: { width, height }, }, }) => {
                this.setState({
                    canvasSize: {
                        x: width,
                        y: height + 125,
                    },
                });
            };
```

**Comment by pke** [comment] 2022-11-14 13:30
This has been fixed in Oktober 21 and this issue should be closed.

**Closed** 2022-11-14 13:33 UTC
